### ISSUE TITLE
Dark theme (via Nginx rev proxy) and some issues

### ISSUE THREAD

**Issue by elmerfds** [scooterpsu/Comixology_Ubooquity_2#4] opened 2019-03-26 01:09 UTC
Hi Scott,

I'm not sure if you have any plans to create a dark version of your theme but I've created one as a stopgap for myself (comic module only so far), which is applied only when accessed via the reverse proxy url.

![image](https://user-images.githubusercontent.com/22656503/54963773-e2fa7e80-4f61-11e9-9a67-461587f2f030.png)

![image](https://user-images.githubusercontent.com/22656503/54963837-1fc67580-4f62-11e9-9858-1bc438238e59.png)

![image](https://user-images.githubusercontent.com/22656503/54964108-15f14200-4f63-11e9-896f-f0d43ba9b587.png)

![image](https://user-images.githubusercontent.com/22656503/54963944-864b9380-4f62-11e9-82e1-42f3a789a535.png)

If you want to try it out, add the following to your ubooquity Nginx reverse proxy block
```
proxy_set_header Accept-Encoding "";
sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://elmerfdz.github.io/themes/ubooquity/comixology/dark-comixology.css"></head>';
sub_filter_once on;
```

**Issues**

1. I'm no CSS expert or anything, with the recent release and inclusion of split search, I'm having a problem overriding the `!important` tag used here (comixology.css:559):

```
.searchPage, #series, #storyarc {
    background-color: #ededed !important;
}
```
and few other places ('remove bookmark' bg colour) but I can live with that but the one above is a dealbreaker.

2. So due to the dark background, I had to create white text versions of SwedishGojira's logos, problem is swapping the logos based on conditions. I'm sure it's possible using js but not sure how to do it, so at the moment, I'm just repalcing the banners with the white versions.

Any suggestions?

**Comment by scooterpsu** [comment] 2019-03-26 01:37
Rather than adding in an additional css file, I think you'd be better off making the changes in comixology.css itself. Overriding an !important can be difficult, that's how they work.

I personally was going for a clone, so I didn't have an intentions of making a dark version. Looks like you're making some impressive progress, so what I'd suggest is this:

Edit your themeScript.js to add

    $('body').addClass('dark');

to line 37 below the loadScript's.

Then you can preface your css with .dark:

    .dark .list-container {

Anything you can't override, change in comixology.css to body:not(.dark) whatever: 

    body:not(.dark) .action-button .action-title {

The logos applying conditionally is on 607 of themeScript, I'd hardcode that for now but it wouldn't be hard to make it check for that when applying them.

This way applying the change is just adding that class, which I can make a setting really easily.

**Comment by scooterpsu** [comment] 2019-03-26 02:22
Changed my suggestion to something more helpful, but I'm guessing the edit didn't trigger an email notification. So this is just to draw your attention to the edited post.

**Comment by scooterpsu** [comment] 2019-03-26 12:26
To expand on my edited comment, I realized "body:not(.dark)" would work for this theme but doesn't leave opportunities for other variants. 

Using the new release, there's also a "themed" class added to body, so anything you are having problems overriding you can add "body:not(.themed)" in front of in comixology.css. Then let me know which are giving issue and I'll add that to the official comixology.css.

Here is a zipped themes folder I used to test. It's your dark-comixology.css renamed to just dark.css.
[themes.zip](https://github.com/scooterpsu/Comixology_Ubooquity_2/files/3008090/themes.zip)

Just add the following to your settings.js:

    var themeVariant="dark";

**Comment by elmerfds** [comment] 2019-03-26 12:41
I was just about to reply to you, had got it working doing the following:

1. Settings.js
`var darkTheme = true;`

2. Adding dark css to themeScript.js
```
        $.ajaxSetup({ cache: false });
        $('head').append('<link rel="stylesheet" href="'+proxyPrefix+'/theme/comixology.css" type="text/css" />');
        if(darkTheme){
            $('head').append('<link rel="stylesheet" href="'+proxyPrefix+'/theme/dark-comixology.css" type="text/css" />');
        }
```

3. Conditional Logos: themeScript.js
```
                /* Set logo depending on Ubooquity settings. */
                if(settingsJSON['isComicsProviderEnabled']&&!settingsJSON['isBooksProviderEnabled']){
                    if(darkTheme){
                        $('.comixology-logo').css("background-image", "url('"+proxyPrefix+"/theme/darkassets/Ubooquity-logo_1_comic_w.png')");
                    }else{
                        $('.comixology-logo').css("background-image", "url('"+proxyPrefix+"/theme/Ubooquity-logo_1_comic.png')");
                    }
                }else if(settingsJSON['isBooksProviderEnabled']&&!settingsJSON['isComicsProviderEnabled']){
                    if(darkTheme){
                        $('.comixology-logo').css("background-image", "url('"+proxyPrefix+"/theme/darkassets/Ubooquity-logo_1_ebook_w.png')");
                    }else{
                        $('.comixology-logo').css("background-image", "url('"+proxyPrefix+"/theme/Ubooquity-logo_1_ebook.png')");
                    }
                }else{
                    if(darkTheme){
                        $('.comixology-logo').css("background-image", "url('"+proxyPrefix+"/theme/darkassets/Ubooquity-logo_1_comic_ebook_w.png')");
                    }else{
                        $('.comixology-logo').css("background-image", "url('"+proxyPrefix+"/theme/Ubooquity-logo_1_comic_ebook.png')");
                    }                    
                }
```
Doing the above, I've had no problem overiding `!important` tags. I'll try your latest release in a bit

[darkassets.zip](https://github.com/scooterpsu/Comixology_Ubooquity_2/files/3008147/darkassets.zip)

**Comment by elmerfds** [comment] 2019-03-26 13:23
I've tried your latest release and it's perfect! mate, I can override !important tags without any issues now.

Really appreciate you adding support for this so quickly. I'll play around with this later, will let you know if any issues :)

Cheers

**Comment by scooterpsu** [comment] 2019-03-26 14:00
Glad it's working for ya! 

Once we've got a variant or 2 to play with, I was thinking it might be cool to make this a drop-down in the footer instead of a settings.js variable. That way it can be user/browser specific and you can switch based on what fits.

**Comment by elmerfds** [comment] 2019-03-26 18:12
I was thinking the same about having an option to switch from the gui itself but would still like an option in settings.js to use any theme as the default.

**Comment by scooterpsu** [comment] 2019-03-26 18:27
Great minds think alike! I just released a version that will pull from an array of theme variants and if there's nothing set, it defaults to themeVariant from settings.js.

To add your theme, just add the name to themeVariants on line 32 of themeScript.js

    var themeVariants=['dark'];

This'll add Default, and dark (or whatever you named yours) to a drop-down in the footer.

**Comment by elmerfds** [comment] 2019-03-26 19:04
I've tried it, it works but there's a small issue.

1. If a themeVariant is set on settings.js (dark) and also added a new test theme variant to themeScript.js. It defaults to dark, which we want. Switching to the test theme variant, it switches to that but when I click on default, instead of switching back to dark, it switches to the original light variant, only after a refresh it goes to the default theme set in settings.js

2. Is it possible to include the option to show the original light theme in the 'theme variant' drop down as well?

**Comment by scooterpsu** [comment] 2019-03-26 19:10
Default should always give the light option, it's hardcoded to do so. That's not pulled from the array, because it's _not_ a variant. :)

The setting in settings.js only sets the _initial_ value. After that it's overridden in a cookie, and it will load the selected preference moving forward. It will pull from settings.js for any new browser/device you access the page from, but then that page will load its stored value moving forward.

**Comment by elmerfds** [comment] 2019-03-26 19:18
Ok that makes sense, I see how it's supposed to work.

I've just notcied that after switching theme variant from browser, it doesn't stick, a refresh or going to another page loads the default set variant in settings.js (this is on the same browser btw, didn't clear cookies).

**Comment by scooterpsu** [comment] 2019-03-26 19:38
Yup, confirmed that on my end (did all my testing without something set in settings.js).

New release should sort that out.

**Comment by elmerfds** [comment] 2019-03-26 19:43
Sweet! working as expected now :) 

cheers

**Comment by elmerfds** [comment] 2019-03-27 17:54
Hi Scott, could you please add these 2 dark theme variants? 
[dark-a.zip](https://github.com/scooterpsu/Comixology_Ubooquity_2/files/3014636/dark-a.zip)
[dark-b.zip](https://github.com/scooterpsu/Comixology_Ubooquity_2/files/3014637/dark-b.zip)

**Comment by scooterpsu** [comment] 2019-03-27 19:42
Awesome work man! I made 2 minor changes (!important on the #playlist li a color), and added a folder of filebrowser/audiobook controls (made them white). I'll push these in a release momentarily.

Edit: found the little triangle at the top of the homepage hover popup:

    .list-content .label:before, .list-content .label:after {
        border-bottom-color: #1F1F1F !important;
    }

[themes.zip](https://github.com/scooterpsu/Comixology_Ubooquity_2/files/3015109/themes.zip)

**Comment by elmerfds** [comment] 2019-03-27 22:34
Thanks for adding the filebrowser/audiobooks assets :)

Forgot to check the login page before sending the theme files over to you, minor additions here:
[themes_css.zip](https://github.com/scooterpsu/Comixology_Ubooquity_2/files/3015492/themes_css.zip)

btw have you tested the themes by setting a default one in settings.js? It's not loading the default theme for me, works fine changing it from the browser though.

Edit:  Tried it in incognito mode and mobile, loads the white theme.

**Comment by scooterpsu** [comment] 2019-03-27 23:17
Yeah not sure why getting that order correct was such a struggle, should be fixed now. And with your fixes I think it's done! :)

**Comment by elmerfds** [comment] 2019-03-27 23:25
yep! looks like that has done the trick, cheers :)

**Closed as completed** 2019-03-28 01:06 UTC
